name: CI Workflow main
on: 
  push:
   branches:
     - 'main'     
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - name: Setup JDK 11
       uses: actions/setup-java@v3
       with:
          java-version: '11'
          distribution: 'zulu'
     - name: Maven Compiler/Test/Package 
       run: mvn --activate-profiles prod package
